import { Check, CircleAlert, Coins, History, RefreshCw, Save, ShieldCheck } from "lucide-react";
import { useCallback, useEffect, useState } from "react";

import { api } from "@/platform/http/api";
import type { QuotaAdjustment, QuotaBinding, QuotaGrant, QuotaPolicy } from "@/shared/types";

const nowInput = () => new Date().toISOString().slice(0, 16);
const tomorrowInput = () => new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString().slice(0, 16);
const toUtc = (value: string) => new Date(value).toISOString();
const displayMicro = (value: number) => `${Number(value).toLocaleString("zh-CN")} μcredits`;

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="quota-field"><span>{label}</span>{children}</label>; }
function Notice({ message }: { message: string }) { return message ? <p className="quota-form-message"><CircleAlert size={14} />{message}</p> : null; }

export function QuotaManagementPage() {
  const [policies, setPolicies] = useState<QuotaPolicy[]>([]);
  const [bindings, setBindings] = useState<QuotaBinding[]>([]);
  const [grants, setGrants] = useState<QuotaGrant[]>([]);
  const [adjustments, setAdjustments] = useState<QuotaAdjustment[]>([]);
  const [error, setError] = useState("");
  const [message, setMessage] = useState("");
  const [policyForm, setPolicyForm] = useState({ code: "student", version: "", name: "", daily: "", monthly: "", request: "", concurrency: "2" });
  const [bindingForm, setBindingForm] = useState({ subject_type: "role", subject_id: "student", policy_id: "", priority: "10" });
  const [grantForm, setGrantForm] = useState({ owner_type: "user", owner_id: "", bucket_type: "daily", amount: "", period_start: nowInput(), period_end: tomorrowInput(), expires_at: "", idempotency_key: "" });
  const [adjustmentForm, setAdjustmentForm] = useState({ owner_type: "user", owner_id: "", bucket_type: "daily", amount: "", period_start: nowInput(), period_end: tomorrowInput(), reason: "", idempotency_key: "" });
  const load = useCallback(async () => {
    setError("");
    try {
      const [policyResult, bindingResult, grantResult, adjustmentResult] = await Promise.all([api.listQuotaPolicies(), api.listQuotaBindings(), api.listQuotaGrants(), api.listQuotaAdjustments()]);
      setPolicies(policyResult.items); setBindings(bindingResult.items); setGrants(grantResult.items); setAdjustments(adjustmentResult.items);
      setBindingForm((current) => ({ ...current, policy_id: current.policy_id || policyResult.items.find((item) => item.status === "active")?.policy_id || "" }));
    } catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)); }
  }, []);
  useEffect(() => { queueMicrotask(() => void load()); }, [load]);
  const savePolicy = async () => {
    try {
      await api.createQuotaPolicy({ code: policyForm.code, version: policyForm.version, name: policyForm.name, request_limit_micro: policyForm.request ? Number(policyForm.request) : null, daily_limit_micro: policyForm.daily ? Number(policyForm.daily) : null, monthly_limit_micro: policyForm.monthly ? Number(policyForm.monthly) : null, concurrency_limit: policyForm.concurrency ? Number(policyForm.concurrency) : null, max_overdraft_micro: 0, allowed_model_profiles: [], unlimited: false, effective_from: toUtc(nowInput()), effective_until: null, status: "draft" });
      setMessage("策略草稿已创建"); await load();
    } catch (reason) { setMessage(reason instanceof Error ? reason.message : String(reason)); }
  };
  const saveBinding = async () => {
    try { await api.bindQuotaPolicy({ subject_type: bindingForm.subject_type, subject_id: bindingForm.subject_id, policy_id: bindingForm.policy_id, priority: Number(bindingForm.priority), effective_from: toUtc(nowInput()), effective_until: null }); setMessage("策略绑定已发布"); await load(); }
    catch (reason) { setMessage(reason instanceof Error ? reason.message : String(reason)); }
  };
  const saveGrant = async () => {
    try { await api.createQuotaGrant({ owner_type: grantForm.owner_type, owner_id: grantForm.owner_id, bucket_type: grantForm.bucket_type, period_start: toUtc(grantForm.period_start), period_end: toUtc(grantForm.period_end), allocated_micro: Number(grantForm.amount), source_type: "grant", source_id: null, effective_from: new Date().toISOString(), expires_at: grantForm.expires_at ? toUtc(grantForm.expires_at) : null, reason: "developer allocation", idempotency_key: grantForm.idempotency_key }); setMessage("额度 Grant 已分配"); await load(); }
    catch (reason) { setMessage(reason instanceof Error ? reason.message : String(reason)); }
  };
  const saveAdjustment = async () => {
    try { await api.createQuotaAdjustment({ owner_type: adjustmentForm.owner_type, owner_id: adjustmentForm.owner_id, bucket_type: adjustmentForm.bucket_type, period_start: toUtc(adjustmentForm.period_start), period_end: toUtc(adjustmentForm.period_end), amount_micro: Number(adjustmentForm.amount), reason: adjustmentForm.reason, idempotency_key: adjustmentForm.idempotency_key }); setMessage("手工调整已记录"); await load(); }
    catch (reason) { setMessage(reason instanceof Error ? reason.message : String(reason)); }
  };
  return <main className="quota-page developer-quota-page">
    <header className="quota-page-header"><div><span className="quota-eyebrow">DEVELOPER CONTROL PLANE</span><h1>额度管理</h1><p>唯一分配入口。策略、工作空间预算、Grant 和手工调整均由开发者发布，并保留操作审计。</p></div><button type="button" onClick={() => void load()}><RefreshCw size={16} />刷新数据</button></header>
    {error && <div className="quota-error" role="alert"><CircleAlert size={17} />{error}</div>}{message && <div className="quota-success"><Check size={17} />{message}</div>}
    <section className="quota-panel"><div className="quota-panel-heading"><div><h2>策略版本</h2><p>发布新版本不会改写历史 Reservation 或 Ledger 快照。</p></div></div><div className="quota-form-grid"><Field label="策略代码"><input value={policyForm.code} onChange={(event) => setPolicyForm({ ...policyForm, code: event.target.value })} /></Field><Field label="版本"><input value={policyForm.version} onChange={(event) => setPolicyForm({ ...policyForm, version: event.target.value })} placeholder="2026.08.30" /></Field><Field label="名称"><input value={policyForm.name} onChange={(event) => setPolicyForm({ ...policyForm, name: event.target.value })} /></Field><Field label="每日上限"><input inputMode="numeric" value={policyForm.daily} onChange={(event) => setPolicyForm({ ...policyForm, daily: event.target.value })} /></Field><Field label="每月上限"><input inputMode="numeric" value={policyForm.monthly} onChange={(event) => setPolicyForm({ ...policyForm, monthly: event.target.value })} /></Field><Field label="单请求上限"><input inputMode="numeric" value={policyForm.request} onChange={(event) => setPolicyForm({ ...policyForm, request: event.target.value })} /></Field><Field label="并发数"><input inputMode="numeric" value={policyForm.concurrency} onChange={(event) => setPolicyForm({ ...policyForm, concurrency: event.target.value })} /></Field></div><button className="quota-primary-button" type="button" onClick={() => void savePolicy()} disabled={!policyForm.code || !policyForm.version || !policyForm.name}><Save size={15} />创建策略草稿</button><div className="quota-table-wrap"><table><thead><tr><th>策略</th><th>版本</th><th>状态</th><th>每日</th><th>操作</th></tr></thead><tbody>{policies.map((policy) => <tr key={policy.policy_id}><td>{policy.name}<small>{policy.code}</small></td><td>v{policy.version}</td><td>{policy.status}</td><td>{policy.daily_limit_micro == null ? "无限" : displayMicro(policy.daily_limit_micro)}</td><td>{policy.status !== "active" && <button type="button" onClick={() => void api.publishQuotaPolicy(policy.policy_id).then(load).catch((reason) => setMessage(reason instanceof Error ? reason.message : String(reason)))}>发布</button>}</td></tr>)}</tbody></table></div></section>
    <section className="quota-panel"><div className="quota-panel-heading"><div><h2>默认 / 角色 / 用户 / 工作空间绑定</h2><p>同一主体的新绑定会关闭重叠旧绑定；多角色只由服务端选一个基础策略。</p></div></div><div className="quota-form-grid"><Field label="主体类型"><select value={bindingForm.subject_type} onChange={(event) => setBindingForm({ ...bindingForm, subject_type: event.target.value })}><option value="default">默认</option><option value="role">角色</option><option value="user">用户</option><option value="workspace">工作空间</option><option value="classroom">课堂</option></select></Field><Field label="主体 ID"><input value={bindingForm.subject_id} onChange={(event) => setBindingForm({ ...bindingForm, subject_id: event.target.value })} /></Field><Field label="策略"><select value={bindingForm.policy_id} onChange={(event) => setBindingForm({ ...bindingForm, policy_id: event.target.value })}>{policies.filter((item) => item.status === "active").map((item) => <option key={item.policy_id} value={item.policy_id}>{item.code} · v{item.version}</option>)}</select></Field><Field label="优先级"><input inputMode="numeric" value={bindingForm.priority} onChange={(event) => setBindingForm({ ...bindingForm, priority: event.target.value })} /></Field></div><button className="quota-primary-button" type="button" onClick={() => void saveBinding()} disabled={!bindingForm.policy_id || !bindingForm.subject_id}><ShieldCheck size={15} />发布绑定</button><div className="quota-table-wrap"><table><thead><tr><th>主体</th><th>策略</th><th>优先级</th><th>有效期</th></tr></thead><tbody>{bindings.map((binding) => <tr key={binding.binding_id}><td>{binding.subject_type} / {binding.subject_id}</td><td>{binding.policy_code} · v{binding.policy_version}</td><td>{binding.priority}</td><td>{new Date(binding.effective_from).toLocaleString("zh-CN")}</td></tr>)}</tbody></table></div></section>
    <section className="quota-panel"><div className="quota-panel-heading"><div><h2>Quota Grant 分配</h2><p>可分配给用户或工作空间，支持有效期和撤销；操作使用幂等键。</p></div></div><div className="quota-form-grid"><Field label="归属类型"><select value={grantForm.owner_type} onChange={(event) => setGrantForm({ ...grantForm, owner_type: event.target.value })}><option value="user">用户</option><option value="workspace">工作空间</option><option value="classroom">课堂</option></select></Field><Field label="归属 ID"><input value={grantForm.owner_id} onChange={(event) => setGrantForm({ ...grantForm, owner_id: event.target.value })} /></Field><Field label="周期"><select value={grantForm.bucket_type} onChange={(event) => setGrantForm({ ...grantForm, bucket_type: event.target.value })}><option value="daily">每日</option><option value="monthly">每月</option></select></Field><Field label="额度"><input inputMode="numeric" value={grantForm.amount} onChange={(event) => setGrantForm({ ...grantForm, amount: event.target.value })} /></Field><Field label="周期开始"><input type="datetime-local" value={grantForm.period_start} onChange={(event) => setGrantForm({ ...grantForm, period_start: event.target.value })} /></Field><Field label="周期结束"><input type="datetime-local" value={grantForm.period_end} onChange={(event) => setGrantForm({ ...grantForm, period_end: event.target.value })} /></Field><Field label="幂等键"><input value={grantForm.idempotency_key} onChange={(event) => setGrantForm({ ...grantForm, idempotency_key: event.target.value })} /></Field></div><button className="quota-primary-button" type="button" onClick={() => void saveGrant()} disabled={!grantForm.owner_id || !grantForm.amount || !grantForm.idempotency_key}><Coins size={15} />分配 Grant</button><div className="quota-table-wrap"><table><thead><tr><th>归属</th><th>额度</th><th>状态</th><th>有效期</th><th>操作</th></tr></thead><tbody>{grants.map((grant) => <tr key={grant.grant_id}><td>{grant.owner_type} / {grant.owner_id}</td><td>{displayMicro(grant.allocated_micro)}</td><td>{grant.status}</td><td>{grant.expires_at ? new Date(grant.expires_at).toLocaleString("zh-CN") : "周期结束"}</td><td>{grant.status === "active" && <button type="button" onClick={() => void api.revokeQuotaGrant(grant.grant_id, `revoke-${grant.grant_id}`).then(load).catch((reason) => setMessage(reason instanceof Error ? reason.message : String(reason)))}>撤销</button>}</td></tr>)}</tbody></table></div></section>
    <section className="quota-panel"><div className="quota-panel-heading"><div><h2>手工调整</h2><p>正数补充额度，负数扣减额度；必须填写原因与幂等键。</p></div></div><div className="quota-form-grid"><Field label="归属类型"><select value={adjustmentForm.owner_type} onChange={(event) => setAdjustmentForm({ ...adjustmentForm, owner_type: event.target.value })}><option value="user">用户</option><option value="workspace">工作空间</option><option value="classroom">课堂</option></select></Field><Field label="归属 ID"><input value={adjustmentForm.owner_id} onChange={(event) => setAdjustmentForm({ ...adjustmentForm, owner_id: event.target.value })} /></Field><Field label="调整量"><input inputMode="numeric" value={adjustmentForm.amount} onChange={(event) => setAdjustmentForm({ ...adjustmentForm, amount: event.target.value })} placeholder="可为负数" /></Field><Field label="原因"><input value={adjustmentForm.reason} onChange={(event) => setAdjustmentForm({ ...adjustmentForm, reason: event.target.value })} /></Field><Field label="幂等键"><input value={adjustmentForm.idempotency_key} onChange={(event) => setAdjustmentForm({ ...adjustmentForm, idempotency_key: event.target.value })} /></Field></div><button className="quota-primary-button" type="button" onClick={() => void saveAdjustment()} disabled={!adjustmentForm.owner_id || !adjustmentForm.amount || !adjustmentForm.reason || !adjustmentForm.idempotency_key}><History size={15} />记录调整</button><div className="quota-table-wrap"><table><thead><tr><th>归属</th><th>调整量</th><th>原因</th><th>操作人</th></tr></thead><tbody>{adjustments.map((item) => <tr key={item.adjustment_id}><td>{item.owner_type} / {item.owner_id}</td><td>{displayMicro(item.amount_micro)}</td><td>{item.reason}</td><td>{item.actor_user_id}</td></tr>)}</tbody></table></div></section>
    <Notice message={message} />
  </main>;
}

export default QuotaManagementPage;
