"""LLM-powered conversation topic summarization.

Replaces the frontend's first-message truncation with a short (<=40 char)
topic line generated by the cheap ``utility`` model after a turn completes.
Generation is idempotent and out-of-order safe: a conditional UPDATE keyed on
the *basis* timestamp (the newest completed turn's ``completed_at``) rejects a
stale summary that finishes after a newer one.
"""

from __future__ import annotations

import asyncio
import re
from datetime import datetime
from typing import Any

from langchain_core.messages import HumanMessage
from sqlalchemy import select, text
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker

from core.prompt_runtime.manager import global_prompt_runtime
from server.agent.llm_factory import get_utility_llm
from server.infrastructure.mysql.models import ConversationModel, TurnModel
from utils.logger import get_logger

logger = get_logger("shiliu.session_summary")

# Trim the learning-context preamble so it does not pollute the prompt.
_LEARNING_CONTEXT_RE = re.compile(r"^<!-- nlp-learning-context:.*? -->\s*", re.S)
_LEARNING_SETTING_RE = re.compile(r"^\[学习设置：.*?\]\s*", re.S)

# Include the first turn (it anchors the topic) plus the most recent few.
_RECENT_TURN_WINDOW = 3
# Recompute only once this many NEW completed turns have accumulated.
_RECOMPUTE_TURN_DELTA = 3
MAX_TITLE_CHARS = 40
MAX_OUTPUT_TOKENS = 80


def _clean_input(text: str) -> str:
    text = _LEARNING_CONTEXT_RE.sub("", text)
    text = _LEARNING_SETTING_RE.sub("", text)
    return re.sub(r"\s+", " ", text).strip()


def _clean_result(text: str) -> str:
    # ``result_text`` is already free of tool JSON / thinking (those live in
    # transcripts), but drop any residual markers and light markdown noise.
    text = re.sub(r"<!--.*?-->", "", text, flags=re.S)
    text = re.sub(r"[#*_`]", "", text)
    return re.sub(r"\s+", " ", text).strip()


def _clean_title(title: str) -> str:
    title = title.strip().strip("\"'“”‘’「」")
    title = re.sub(r"^[#*\-\s]+", "", title)
    title = re.sub(r"[#*\-\s]+$", "", title)
    return re.sub(r"\s+", " ", title).strip()[:MAX_TITLE_CHARS]


def _select_turns(turns: list[TurnModel]) -> list[TurnModel]:
    if not turns:
        return []
    selected = [turns[0]]
    for turn in turns[-_RECENT_TURN_WINDOW:]:
        if turn.id != turns[0].id:
            selected.append(turn)
    return selected


def _render_turns(turns: list[TurnModel]) -> str:
    parts: list[str] = []
    for turn in turns:
        user = _clean_input(turn.input_text)
        if user:
            parts.append(f"[user]: {user}")
        if turn.result_text:
            assistant = _clean_result(turn.result_text)
            if assistant:
                parts.append(f"[assistant]: {assistant}")
    return "\n".join(parts)


def _decide(
    turns: list[TurnModel], title_updated_at: datetime | None
) -> datetime | None:
    """Return the summary basis (newest completed turn) if generation is due.

    The first summary runs after the first completed turn; later ones only once
    ``_RECOMPUTE_TURN_DELTA`` new turns have completed since the last basis.
    """
    if not turns:
        return None
    basis = max(
        (t.completed_at for t in turns if t.completed_at is not None), default=None
    )
    if basis is None:
        return None
    if title_updated_at is not None:
        new_since = sum(
            1
            for t in turns
            if t.completed_at is not None and t.completed_at > title_updated_at
        )
        if new_since < _RECOMPUTE_TURN_DELTA:
            return None
    return basis


async def _load_state(
    session: AsyncSession, session_id: str
) -> tuple[datetime | None, list[TurnModel]]:
    title_updated_at = (
        await session.execute(
            select(ConversationModel.title_updated_at).where(
                ConversationModel.id == session_id
            )
        )
    ).scalar_one_or_none()
    turns = list(
        (
            await session.execute(
                select(TurnModel)
                .where(
                    TurnModel.conversation_id == session_id,
                    TurnModel.status == "completed",
                )
                .order_by(TurnModel.created_at, TurnModel.id)
            )
        ).scalars().all()
    )
    return title_updated_at, turns


async def _generate_title(text: str, llm: Any) -> str | None:
    prompt = global_prompt_runtime.render("session.summary", conversation=text)
    response = await llm.ainvoke(
        [HumanMessage(content=prompt)], max_tokens=MAX_OUTPUT_TOKENS
    )
    return _clean_title(str(getattr(response, "content", "") or "")) or None


async def _write_title(
    session: AsyncSession, session_id: str, title: str, basis: datetime
) -> bool:
    result = await session.execute(
        text(
            "UPDATE nlp_conversations SET title=:title, title_updated_at=:basis "
            "WHERE id=:id AND (title_updated_at IS NULL OR title_updated_at < :basis)"
        ),
        {"title": title, "basis": basis, "id": session_id},
    )
    return result.rowcount == 1


async def build_conversation_text(
    session_id: str, session_factory: async_sessionmaker[AsyncSession]
) -> str:
    """Render the first + most recent turns of a session as prompt text."""
    async with session_factory() as session:
        _title_updated_at, turns = await _load_state(session, session_id)
    return _render_turns(_select_turns(turns))


async def generate_and_store_summary(
    session_id: str, session_factory: async_sessionmaker[AsyncSession]
) -> bool:
    """Generate a topic title and conditionally store it.  Never raises."""
    try:
        async with session_factory() as session:
            title_updated_at, turns = await _load_state(session, session_id)
        basis = _decide(turns, title_updated_at)
        if basis is None:
            return False
        text = _render_turns(_select_turns(turns))
        if not text:
            return False
        title = await _generate_title(text, get_utility_llm())
        if title is None:
            return False
        async with session_factory.begin() as session:
            return await _write_title(session, session_id, title, basis)
    except asyncio.CancelledError:
        raise
    except Exception:
        logger.exception("session summary generation failed", session_id=session_id)
        return False


def schedule_summary(
    session_factory: async_sessionmaker[AsyncSession], session_id: str
) -> None:
    """Fire-and-forget summary scheduling; safe to call from any async context."""
    asyncio.create_task(
        generate_and_store_summary(session_id, session_factory),
        name=f"session-summary:{session_id}",
    )
