import { AlertCircle, BarChart3, BookOpen, ChevronLeft, Download, FileQuestion, FileText, GraduationCap, LayoutDashboard, Lightbulb, RefreshCw, Save, Search, Sparkles, Target, TrendingUp, Users } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";

import { api, ensureAuth } from "@/lib/api";
import type { ClassifiedQuestion, TeacherDistribution, TeacherOverview, TeachingGoals } from "@/lib/types";

type TeacherPage = "overview" | "courses" | "prompts" | "questions" | "reports";
const NAV: Array<{ page: TeacherPage; label: string; icon: typeof LayoutDashboard }> = [
  { page: "overview", label: "教师首页", icon: LayoutDashboard },
  { page: "courses", label: "课程与目标", icon: BookOpen },
  { page: "prompts", label: "Prompt 模板", icon: Sparkles },
  { page: "questions", label: "学生问题", icon: FileQuestion },
  { page: "reports", label: "学习分析", icon: BarChart3 },
];

function currentPage(): TeacherPage { const value = location.pathname.split("/")[2] as TeacherPage | undefined; return NAV.some((item) => item.page === value) ? value! : "overview"; }
function formatTime(value: string) { return new Intl.DateTimeFormat("zh-CN", { month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit" }).format(new Date(value)); }
function Difficulty({ value }: { value: string }) { const labels: Record<string, string> = { beginner: "入门", intermediate: "进阶", advanced: "深入" }; return <span className={`teacher-difficulty ${value}`}>{labels[value] ?? value}</span>; }

function Distribution({ title, items, color = "violet" }: { title: string; items: TeacherDistribution[]; color?: string }) {
  const max = Math.max(1, ...items.map((item) => item.count));
  return <section className="teacher-panel"><header><h2>{title}</h2></header><div className="teacher-distribution">{items.length ? items.map((item) => <article key={item.name}><div><strong>{item.name}</strong><span>{item.count} · {item.percentage}%</span></div><i><b className={color} style={{ width: `${item.count / max * 100}%` }} /></i></article>) : <p className="teacher-empty-inline">暂无统计数据</p>}</div></section>;
}
function OverviewPage({ data, navigate }: { data: TeacherOverview; navigate: (page: TeacherPage) => void }) {
  return <div className="teacher-stack"><section className="teacher-welcome"><div><span>TEACHER MODE</span><h1>{data.goals.course_title || "NLP 教学空间"}</h1><p>{data.goals.description || "配置教学目标，并从学生真实问题中发现课程改进方向。"}</p></div><GraduationCap size={64} /></section><div className="teacher-kpis"><article><FileQuestion /><span>学生问题</span><strong>{data.summary.questions}</strong><small>最近 {data.period_days} 天</small></article><article><Users /><span>活跃学生</span><strong>{data.summary.students}</strong><small>{data.summary.sessions} 个会话</small></article><article><TrendingUp /><span>高频问题</span><strong>{data.frequent_questions.filter((item) => item.count > 1).length}</strong><small>重复提问聚类</small></article><article className={data.summary.error_questions ? "warning" : ""}><AlertCircle /><span>异常问题</span><strong>{data.summary.error_questions}</strong><small>回答失败或错误</small></article></div><div className="teacher-two-column"><section className="teacher-panel"><header><div><h2>教学目标</h2><p>当前课程希望学生掌握的能力</p></div><button type="button" onClick={() => navigate("courses")}>编辑目标</button></header><div className="teacher-objectives">{data.goals.objectives.length ? data.goals.objectives.map((objective, index) => <article key={objective}><span>{index + 1}</span>{objective}</article>) : <p className="teacher-empty-inline">尚未配置教学目标</p>}</div></section><section className="teacher-panel"><header><div><h2>需要关注的知识点</h2><p>根据重复、难题和错误自动推断</p></div><button type="button" onClick={() => navigate("reports")}>查看分析</button></header><div className="teacher-weak-preview">{data.weak_topics.slice(0, 5).map((item) => <article key={item.topic}><span className={item.risk}>{item.risk}</span><strong>{item.topic}</strong><small>{item.questions} 个问题 · 分数 {item.score}</small></article>)}{!data.weak_topics.length && <p className="teacher-empty-inline">积累问题后将自动生成</p>}</div></section></div><Distribution title="主题概览" items={data.topic_distribution.slice(0, 8)} /></div>;
}

function GoalsPage({ data, onSave }: { data: TeacherOverview; onSave: (goals: Omit<TeachingGoals, "workspace_id">) => Promise<void> }) {
  const [form, setForm] = useState(data.goals); const [saving, setSaving] = useState(false); const [saved, setSaved] = useState(false);
  const lines = (value: string) => value.split("\n").map((item) => item.trim()).filter(Boolean);
  return <div className="teacher-stack"><section className="teacher-panel teacher-form"><header><div><h2>教学目标配置</h2><p>当前保存在本地 Gateway 设置中；未来可直接迁移到 Course 数据库。</p></div></header><label><span>课程名称</span><input value={form.course_title} onChange={(event) => setForm({ ...form, course_title: event.target.value })} /></label><label><span>课程说明</span><textarea rows={3} value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} /></label><div className="teacher-form-row"><label><span>目标难度</span><select value={form.target_level} onChange={(event) => setForm({ ...form, target_level: event.target.value as TeachingGoals["target_level"] })}><option value="beginner">入门</option><option value="intermediate">进阶</option><option value="advanced">深入</option></select></label><label><span>重点主题（每行一个）</span><textarea rows={4} value={form.focus_topics.join("\n")} onChange={(event) => setForm({ ...form, focus_topics: lines(event.target.value) })} /></label></div><label><span>学习目标（每行一个）</span><textarea rows={6} value={form.objectives.join("\n")} onChange={(event) => setForm({ ...form, objectives: lines(event.target.value) })} /></label><div className="teacher-form-actions"><button type="button" disabled={saving || !form.course_title.trim()} onClick={async () => { setSaving(true); setSaved(false); await onSave({ course_title: form.course_title, description: form.description, objectives: form.objectives, focus_topics: form.focus_topics, target_level: form.target_level }); setSaving(false); setSaved(true); }}><Save size={15} />{saving ? "保存中…" : "保存教学目标"}</button>{saved && <span>已保存</span>}</div></section><section className="teacher-panel"><header><h2>课程列表</h2></header><div className="teacher-placeholder"><BookOpen /><strong>课程数据接口已预留</strong><p>`GET /api/v1/teacher/courses` 已建立。接入正式课程数据库后可在这里管理班级、章节和学生分配。</p></div></section></div>;
}

function QuestionTable({ questions }: { questions: ClassifiedQuestion[] }) {
  const [query, setQuery] = useState(""); const [topic, setTopic] = useState("all"); const [difficulty, setDifficulty] = useState("all"); const topics = [...new Set(questions.map((item) => item.topic))]; const visible = questions.filter((item) => (topic === "all" || item.topic === topic) && (difficulty === "all" || item.difficulty === difficulty) && `${item.question} ${item.topic} ${item.question_type} ${item.keywords.join(" ")}`.toLowerCase().includes(query.toLowerCase()));
  return <section className="teacher-panel"><header><div><h2>学生问题记录</h2><p>自动分类来自本地规则；未来可替换为模型分类器。</p></div><div className="teacher-filters"><label><Search size={14} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜索问题或关键词" /></label><select value={topic} onChange={(event) => setTopic(event.target.value)}><option value="all">全部主题</option>{topics.map((item) => <option key={item}>{item}</option>)}</select><select value={difficulty} onChange={(event) => setDifficulty(event.target.value)}><option value="all">全部难度</option><option value="beginner">入门</option><option value="intermediate">进阶</option><option value="advanced">深入</option></select></div></header><div className="teacher-table"><table><thead><tr><th>问题</th><th>主题 / 类型</th><th>难度</th><th>关键词</th><th>时间</th></tr></thead><tbody>{visible.map((item) => <tr key={item.turn_id}><td><strong>{item.question}</strong><small>{item.session_id.slice(0, 12)} · {item.status}</small></td><td>{item.topic}<small>{item.question_type}</small></td><td><Difficulty value={item.difficulty} /></td><td><div className="teacher-tags">{item.keywords.slice(0, 3).map((word) => <span key={word}>{word}</span>)}</div></td><td>{formatTime(item.created_at)}</td></tr>)}</tbody></table>{!visible.length && <div className="teacher-placeholder"><FileQuestion /><strong>暂无匹配问题</strong></div>}</div></section>;
}

function ReportsPage({ data }: { data: TeacherOverview }) { const exportReport = () => { const blob = new Blob([JSON.stringify(data, null, 2)], { type: "application/json" }); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = `nlp-teaching-report-${new Date().toISOString().slice(0, 10)}.json`; link.click(); URL.revokeObjectURL(link.href); }; return <div className="teacher-stack"><section className="teacher-panel"><header><div><h2>学生薄弱知识点</h2><p>综合提问次数、重复问题、难题和回答异常形成风险分数。</p></div><button type="button" onClick={exportReport}><Download size={14} />导出报告</button></header><div className="teacher-weak-grid">{data.weak_topics.map((item) => <article key={item.topic}><div><span className={item.risk}>{item.risk}</span><strong>{item.topic}</strong><b>{item.score}</b></div><p>{item.questions} 个问题 · {item.repeat_questions} 次重复 · {item.errors} 次异常 · {item.sessions} 个会话</p></article>)}</div></section><section className="teacher-panel"><header><div><h2>高频问题</h2><p>规范化问题文本后形成的重复问题聚类</p></div></header><div className="teacher-frequent">{data.frequent_questions.slice(0, 12).map((item, index) => <article key={`${item.question}-${index}`}><b>{item.count}</b><span><strong>{item.question}</strong><small>{item.topic} · {item.question_type}</small></span></article>)}</div></section><div className="teacher-two-column"><Distribution title="问题难度统计" items={data.difficulty_distribution} color="blue" /><Distribution title="问题类型统计" items={data.type_distribution} color="green" /></div><Distribution title="主题统计" items={data.topic_distribution} /></div>; }

function PromptsPage() { return <div className="teacher-stack"><section className="teacher-panel"><header><h2>Prompt / 课程模板</h2></header><div className="teacher-placeholder"><Lightbulb /><strong>模板接口已预留</strong><p>`GET /api/v1/teacher/prompts` 已建立。后续可增加课程系统提示词、章节助教模板和版本管理。</p></div></section><section className="teacher-panel"><header><h2>报告模板</h2></header><div className="teacher-placeholder"><FileText /><strong>报告生成边界已建立</strong><p>当前分析报告可导出 JSON；正式数据库接入后可生成学生、班级和课程维度报告。</p></div></section></div>; }

export function TeacherWorkspace() {
  const [page, setPage] = useState<TeacherPage>(currentPage); const [data, setData] = useState<TeacherOverview | null>(null); const [days, setDays] = useState(30); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { const auth = await ensureAuth(); if (!auth.roles.some((role) => role === "admin" || role === "teacher")) throw new Error("当前账户没有教师权限"); setData(await api.getTeacherOverview("default", days)); } catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)); } finally { setLoading(false); } }, [days]);
  useEffect(() => { queueMicrotask(() => void load()); }, [load]); useEffect(() => { const listener = () => setPage(currentPage()); addEventListener("popstate", listener); return () => removeEventListener("popstate", listener); }, []);
  const navigate = (next: TeacherPage) => { history.pushState({}, "", next === "overview" ? "/teacher" : `/teacher/${next}`); setPage(next); };
  const saveGoals = async (goals: Omit<TeachingGoals, "workspace_id">) => { const result = await api.updateTeachingGoals("default", goals); setData((current) => current ? { ...current, goals: result.goals, revision: result.revision, updated_at: result.updated_at } : current); };
  const content = useMemo(() => { if (!data) return null; if (page === "courses") return <GoalsPage data={data} onSave={saveGoals} />; if (page === "prompts") return <PromptsPage />; if (page === "questions") return <QuestionTable questions={data.questions} />; if (page === "reports") return <ReportsPage data={data} />; return <OverviewPage data={data} navigate={navigate} />; }, [data, page]);
  return <div className="teacher-shell"><aside className="teacher-nav"><div className="teacher-brand"><GraduationCap /><span><strong>NLP 教师空间</strong><small>Teacher workspace</small></span></div><nav>{NAV.map(({ page: itemPage, label, icon: Icon }) => <button className={page === itemPage ? "active" : ""} type="button" key={itemPage} onClick={() => navigate(itemPage)}><Icon size={17} />{label}</button>)}</nav><div className="teacher-nav-note"><Target /><p>当前为本地单用户模式<br />数据范围：default workspace</p></div><a href="/"><ChevronLeft size={16} />返回学生模式</a></aside><main className="teacher-main"><header className="teacher-topbar"><div><h1>{NAV.find((item) => item.page === page)?.label}</h1><span>default workspace</span></div><label>统计周期<select value={days} onChange={(event) => setDays(Number(event.target.value))}><option value={7}>7 天</option><option value={30}>30 天</option><option value={90}>90 天</option></select></label><button type="button" onClick={() => void load()} disabled={loading}><RefreshCw className={loading ? "spin" : ""} size={15} />刷新</button></header><div className="teacher-content">{loading && !data ? <div className="teacher-state"><RefreshCw className="spin" />正在整理教学数据…</div> : error ? <div className="teacher-state error"><AlertCircle /><strong>无法进入教师模式</strong><p>{error}</p></div> : content}</div></main></div>;
}
