import { Activity, AlertTriangle, Bot, Clock3, Database, Gauge, HardDrive, Radio, RefreshCw, Search, Server, Timer, X, Zap } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import { authenticate, monitorApi, type ErrorRow, type Overview, type SessionRow, type TelemetryEvent, type Trace, type TraceDetail, type UsageRow } from "./api";

type Page = "overview" | "traces" | "sessions" | "errors" | "events" | "storage";
const NAV: Array<{ page: Page; label: string; icon: typeof Gauge }> = [{ page: "overview", label: "系统总览", icon: Gauge }, { page: "traces", label: "Trace 查询", icon: Activity }, { page: "sessions", label: "Sessions", icon: Bot }, { page: "errors", label: "错误分析", icon: AlertTriangle }, { page: "events", label: "实时事件", icon: Radio }, { page: "storage", label: "数据留存", icon: HardDrive }];

function fmt(value: number | null | undefined, suffix = "") { return value == null ? "—" : `${value.toLocaleString()}${suffix}`; }
function time(value?: string) { return value ? new Intl.DateTimeFormat("zh-CN", { month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit", second: "2-digit" }).format(new Date(value)) : "—"; }
function Status({ value }: { value: string }) { return <span className={`mon-status ${value}`}>{value}</span>; }
function Empty({ text }: { text: string }) { return <div className="mon-empty"><Database /><span>{text}</span></div>; }

function OverviewPage({ data, usage }: { data: Overview; usage: UsageRow[] }) {
  const max = Math.max(1, ...usage.map((row) => row.total_tokens));
  return <div className="mon-stack"><div className="mon-kpis"><article><Zap /><span>请求</span><strong>{fmt(data.requests)}</strong><small>{data.period_days} 天</small></article><article><Timer /><span>P95 响应</span><strong>{fmt(data.latency_ms.p95, " ms")}</strong><small>P50 {fmt(data.latency_ms.p50, " ms")}</small></article><article><Clock3 /><span>P95 首 Token</span><strong>{fmt(data.ttft_ms.p95, " ms")}</strong><small>P50 {fmt(data.ttft_ms.p50, " ms")}</small></article><article className={data.error_rate > .05 ? "danger" : ""}><AlertTriangle /><span>错误率</span><strong>{(data.error_rate * 100).toFixed(2)}%</strong><small>{data.errors} errors</small></article></div><section className="mon-panel"><header><div><h2>Token 与缓存</h2><p>Provider 返回的输入、输出、推理和 KV Cache 命中数据</p></div></header><div className="mon-token-grid">{Object.entries(data.tokens).map(([key, value]) => <article key={key}><span>{key.replaceAll("_", " ")}</span><strong>{fmt(value)}</strong></article>)}</div></section><section className="mon-panel"><header><div><h2>用量趋势</h2><p>按组件与模型聚合的本地 Token 记录</p></div></header>{usage.length ? <div className="mon-bars">{usage.slice(-24).map((row, index) => <div key={`${row.day}-${row.component}-${row.name}-${index}`} title={`${row.day} ${row.name}: ${row.total_tokens}`}><span style={{ height: `${Math.max(3, row.total_tokens / max * 100)}%` }} /><small>{row.component.slice(0, 3)}</small></div>)}</div> : <Empty text="还没有 Token 用量数据" />}</section></div>;
}

function TraceTable({ traces, onOpen }: { traces: Trace[]; onOpen: (trace: Trace) => void }) {
  const [query, setQuery] = useState(""); const visible = traces.filter((trace) => `${trace.trace_id} ${trace.session_id} ${trace.turn_id} ${trace.status}`.toLowerCase().includes(query.toLowerCase()));
  return <section className="mon-panel"><header><div><h2>请求 Trace</h2><p>从 Coordinator 到 Worker、模型与工具的完整链路</p></div><label className="mon-search"><Search size={14} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Trace / Session / Turn" /></label></header><div className="mon-table"><table><thead><tr><th>时间</th><th>Trace</th><th>状态</th><th>响应 / TTFT</th><th>Token</th><th>Session</th></tr></thead><tbody>{visible.map((trace) => <tr key={trace.trace_id} onClick={() => onOpen(trace)}><td>{time(trace.started_at)}</td><td><code>{trace.trace_id.slice(0, 12)}</code><small>{trace.source}</small></td><td><Status value={trace.status} /></td><td>{fmt(trace.duration_ms, " ms")}<small>{fmt(trace.ttft_ms, " ms")}</small></td><td>{fmt(trace.total_tokens)}<small>cached {fmt(trace.cached_tokens)}</small></td><td><code>{trace.session_id.slice(0, 12)}</code></td></tr>)}</tbody></table>{!visible.length && <Empty text="没有匹配的 Trace" />}</div></section>;
}

function TraceDrawer({ detail, onClose }: { detail: TraceDetail; onClose: () => void }) { const start = new Date(detail.trace.started_at).getTime(); const total = Math.max(detail.trace.duration_ms ?? 1, 1); return <><button className="mon-drawer-backdrop" type="button" onClick={onClose} aria-label="关闭" /><aside className="mon-drawer"><header><div><span>TRACE DETAIL</span><h2>{detail.trace.trace_id}</h2></div><button type="button" onClick={onClose}><X /></button></header><div className="mon-drawer-body"><div className="mon-detail-grid"><article><span>状态</span><Status value={detail.trace.status} /></article><article><span>总耗时</span><strong>{fmt(detail.trace.duration_ms, " ms")}</strong></article><article><span>首 Token</span><strong>{fmt(detail.trace.ttft_ms, " ms")}</strong></article><article><span>总 Token</span><strong>{fmt(detail.trace.total_tokens)}</strong></article></div><section><h3>Coordinator / Worker / Tool 时间线</h3><div className="mon-timeline">{detail.spans.map((span) => { const offset = Math.max(0, new Date(span.started_at).getTime() - start); return <article key={span.span_id}><div><strong>{span.name}</strong><span>{span.kind} · {span.worker_id ?? "coordinator"}</span></div><Status value={span.status} /><div className="mon-track"><i style={{ marginLeft: `${offset / total * 100}%`, width: `${Math.max(1, (span.duration_ms ?? 1) / total * 100)}%` }} /></div><small>{fmt(span.duration_ms, " ms")} · attempt {span.attempt} · {fmt(span.total_tokens)} tokens</small></article>; })}</div></section><section><h3>事件</h3><div className="mon-event-list">{detail.events.map((event) => <article key={event.event_id}><time>{time(event.timestamp)}</time><Status value={event.level} /><strong>{event.name}</strong><pre>{JSON.stringify(event.payload, null, 2)}</pre></article>)}</div></section><details><summary>原始 Trace / Tool JSON</summary><pre className="mon-json">{JSON.stringify(detail, null, 2)}</pre></details></div></aside></>; }

export function MonitorApp() {
  const [page, setPage] = useState<Page>("overview"); const [days, setDays] = useState(30); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [overview, setOverview] = useState<Overview | null>(null); const [traces, setTraces] = useState<Trace[]>([]); const [usage, setUsage] = useState<UsageRow[]>([]); const [sessions, setSessions] = useState<SessionRow[]>([]); const [errors, setErrors] = useState<ErrorRow[]>([]); const [events, setEvents] = useState<TelemetryEvent[]>([]); const [storage, setStorage] = useState<Record<string, unknown>>({}); const [detail, setDetail] = useState<TraceDetail | null>(null); const [live, setLive] = useState(false);
  const load = useCallback(async () => { setLoading(true); setError(""); try { await authenticate(); const [o, t, u, s, e, ev, st] = await Promise.all([monitorApi.overview(days), monitorApi.traces(), monitorApi.usage(days), monitorApi.sessions(days), monitorApi.errors(days), monitorApi.events(), monitorApi.storage()]); setOverview(o); setTraces(t.items); setUsage(u.items); setSessions(s.items); setErrors(e.items); setEvents(ev.items); setStorage(st); } catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)); } finally { setLoading(false); } }, [days]);
  useEffect(() => { queueMicrotask(() => void load()); }, [load]);
  useEffect(() => { if (!overview) return; const protocol = location.protocol === "https:" ? "wss:" : "ws:"; const socket = new WebSocket(`${protocol}//${location.host}/ws/observability`); socket.onopen = () => setLive(true); socket.onclose = () => setLive(false); socket.onmessage = (message) => { const frame = JSON.parse(message.data) as { type: string; payload: TelemetryEvent }; if (frame.type === "telemetry.event") setEvents((current) => [frame.payload, ...current.filter((item) => item.event_id !== frame.payload.event_id)].slice(0, 300)); }; return () => socket.close(); }, [overview]);
  const openTrace = async (trace: Trace) => setDetail(await monitorApi.trace(trace.trace_id));
  const pageContent = useMemo(() => { if (!overview) return null; if (page === "traces") return <TraceTable traces={traces} onOpen={(trace) => void openTrace(trace)} />; if (page === "sessions") return <section className="mon-panel"><header><div><h2>活跃 Session</h2><p>请求量、错误、平均响应与 Token</p></div></header><div className="mon-table"><table><thead><tr><th>Session</th><th>用户 / Workspace</th><th>Turn</th><th>错误</th><th>平均响应</th><th>Token</th><th>最后活跃</th></tr></thead><tbody>{sessions.map((row) => <tr key={row.session_id}><td><code>{row.session_id}</code></td><td>{row.user_id}<small>{row.workspace_id} · {row.channel}</small></td><td>{row.turns}</td><td>{row.errors}</td><td>{fmt(row.avg_duration_ms, " ms")}</td><td>{fmt(row.total_tokens)}</td><td>{time(row.last_seen)}</td></tr>)}</tbody></table>{!sessions.length && <Empty text="没有 Session 数据" />}</div></section>; if (page === "errors") return <section className="mon-panel"><header><div><h2>错误、超时与重试</h2><p>按组件和错误类型聚合，点击样例 Trace 进入完整链路</p></div></header><div className="mon-error-grid">{errors.map((row) => <button key={`${row.error_kind}-${row.kind}-${row.name}`} type="button" onClick={() => { const trace = traces.find((item) => item.trace_id === row.sample_trace_id); if (trace) void openTrace(trace); }}><AlertTriangle /><span><strong>{row.error_kind}</strong><small>{row.kind} · {row.name}</small></span><b>{row.count}</b><time>{time(row.last_seen)}</time></button>)}</div>{!errors.length && <Empty text="当前周期没有错误" />}</section>; if (page === "events") return <section className="mon-panel"><header><div><h2>日志与实时事件流</h2><p><i className={`mon-live-dot ${live ? "on" : ""}`} />{live ? "WebSocket 已连接" : "实时连接已断开"}</p></div></header><div className="mon-event-list live">{events.map((event) => <article key={event.event_id}><time>{time(event.timestamp)}</time><Status value={event.level} /><strong>{event.name}</strong><code>{event.trace_id?.slice(0, 10)}</code><pre>{JSON.stringify(event.payload)}</pre></article>)}</div></section>; if (page === "storage") return <section className="mon-panel"><header><div><h2>数据留存与清理</h2><p>Telemetry SQLite 大小、队列、丢弃事件和表记录数</p></div></header><div className="mon-storage"><Json value={storage} /><button type="button" onClick={async () => { if (confirm(`清理 ${days} 天以前的 Trace 与 Event？`)) { setStorage(await monitorApi.prune(days, days)); } }}><HardDrive size={16} />按当前周期清理过期数据</button></div></section>; return <OverviewPage data={overview} usage={usage} />; }, [days, errors, events, live, overview, page, sessions, storage, traces, usage]);
  return <div className="monitor-shell"><aside className="monitor-nav"><div className="monitor-brand"><Server /><span><strong>NLP Monitor</strong><small>OBSERVABILITY · 8766</small></span></div><nav>{NAV.map(({ page: item, label, icon: Icon }) => <button className={page === item ? "active" : ""} type="button" key={item} onClick={() => setPage(item)}><Icon size={17} />{label}</button>)}</nav><a href="http://127.0.0.1:8765/developer">返回控制面</a></aside><main><header className="monitor-top"><div><h1>{NAV.find((item) => item.page === page)?.label}</h1><span><i className={`mon-live-dot ${live ? "on" : ""}`} />{live ? "实时" : "离线"}</span></div><label>统计周期<select value={days} onChange={(event) => setDays(Number(event.target.value))}><option value={1}>24 小时</option><option value={7}>7 天</option><option value={30}>30 天</option><option value={90}>90 天</option></select></label><button type="button" onClick={() => void load()} disabled={loading}><RefreshCw className={loading ? "spin" : ""} />刷新</button></header><div className="monitor-content">{error ? <div className="mon-fatal"><AlertTriangle /><strong>监控数据加载失败</strong><p>{error}</p></div> : loading && !overview ? <div className="mon-fatal"><RefreshCw className="spin" /><strong>正在连接 Monitor</strong></div> : pageContent}</div></main>{detail && <TraceDrawer detail={detail} onClose={() => setDetail(null)} />}</div>;
}
function Json({ value }: { value: unknown }) { return <pre className="mon-json">{JSON.stringify(value, null, 2)}</pre>; }
