import { useEffect, type ReactNode } from "react";
import { useTranslation } from "react-i18next";

// Some student components predate i18n and still contain static Chinese copy.
// This bridge keeps those legacy labels in sync while they are progressively
// moved to translation keys. It never touches messages generated by users/models.
const zhToEn: Record<string, string> = {
  "NLP 学习助手": "NLP Learning Assistant", "新建对话": "New chat", "新建分类": "New category", "搜索": "Search", "设置": "Settings", "未分类": "Uncategorized", "归档对话": "Archived chats", "返回最近对话": "Recent chats", "新的学习对话": "New learning chat", "重命名": "Rename", "收藏": "Favorite", "取消收藏": "Unfavorite", "归档": "Archive", "移出归档": "Unarchive", "删除": "Delete", "移动到分类": "Move to category", "请输入分类名称": "Enter a category name", "重命名分类": "Rename category", "关闭侧栏": "Close sidebar", "展开侧栏": "Expand sidebar", "折叠侧栏": "Collapse sidebar",
  "NLP 基础": "NLP Fundamentals", "文本分类": "Text Classification", "词向量与表示学习": "Word Vectors & Representation Learning", "大语言模型": "Large Language Models", "入门": "Beginner", "进阶": "Intermediate", "深入": "Advanced", "讲解模式": "Explanation mode", "引导模式": "Guided mode", "练习模式": "Practice mode", "复习模式": "Review mode",
  "偏好设置": "Preferences", "学习空间": "Learning space", "通用": "General", "外观": "Appearance", "对话与流式": "Chat & streaming", "学习体验": "Learning experience", "数据与隐私": "Data & privacy", "高级设置": "Advanced", "意见反馈": "Feedback", "版本与更新": "Version & updates", "界面语言": "Interface language", "阅读语言": "Reading language", "当前版本": "Current version", "本次更新与修复": "Updates & fixes", "提交你的建议": "Share your feedback", "发布意见": "Submit feedback",
  "浅色": "Light", "深色": "Dark", "跟随系统": "System", "前往开发者工作台": "Open developer workspace", "进入教师模式": "Open teacher mode", "已是当前版本": "You're up to date", "学习记录": "Learning record", "已连接": "Connected", "正在连接": "Connecting", "正在恢复连接": "Reconnecting", "离线": "Offline",
  "本次学习": "This learning session", "学习目标": "Learning goal", "已涉及概念": "Concepts covered", "完成一次对话后自动整理": "Generated automatically after a completed chat", "待复习：": "Review later: ", "学习进度": "Learning progress", "对话摘要": "Chat summary", "尚未生成学习摘要。": "No learning summary yet.", "巩固练习": "Practice", "生成练习": "Generate exercise", "检查理解": "Check understanding", "导出 Markdown 学习报告": "Export Markdown learning report",
};
const enToZh = Object.fromEntries(Object.entries(zhToEn).map(([zh, en]) => [en, zh]));

function translateText(root: Node, dictionary: Record<string, string>) {
  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
  const nodes: Text[] = [];
  while (walker.nextNode()) nodes.push(walker.currentNode as Text);
  for (const node of nodes) {
    const original = node.nodeValue ?? "";
    const translated = dictionary[original.trim()];
    if (translated) node.nodeValue = original.replace(original.trim(), translated);
  }
}

export function StaticUiBridge({ children }: { children: ReactNode }) {
  const { i18n } = useTranslation();
  useEffect(() => {
    if (location.pathname.startsWith("/developer") || location.pathname.startsWith("/teacher")) return;
    const dictionary = i18n.language.startsWith("zh") ? enToZh : zhToEn;
    const apply = () => translateText(document.getElementById("root")!, dictionary);
    apply();
    const observer = new MutationObserver(apply);
    observer.observe(document.getElementById("root")!, { childList: true, subtree: true, characterData: true });
    return () => observer.disconnect();
  }, [i18n.language]);
  return <>{children}</>;
}
